//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.12 at 04:54:42 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://speller.yandex.net/services/spellservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.springsoapslient.wsdl;
